workspace(name = "com_vmware_blackduckdemo")

load("@bazel_tools//tools/build_defs/repo:jvm.bzl", "jvm_maven_import_external")

jvm_maven_import_external(
    name = "commons_collections",
    artifact = "commons-collections:commons-collections:3.2.2",
    licenses = ["notice"],  # apache license, version 2.0
    server_urls = ["https://repo1.maven.org/maven2"],
)

jvm_maven_import_external(
    name = "commons_collections4",
    artifact = "org.apache.commons:commons-collections4:4.3",
    licenses = ["notice"],  # apache license, version 2.0
    server_urls = ["https://repo1.maven.org/maven2"],
)
