maven_jar(
    name = "com_google_guava_guava",
    artifact = "com.google.guava:guava:18.0"
)

maven_jar(
    name = "org_apache_commons_commons_io",
    artifact = "org.apache.commons:commons-io:1.3.2"
)
